; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 10 2020 05:47:28 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAE5HA6H6BVT4:
	dc.w DATAE5HA6H6BVT4_0-DATAE5HA6H6BVT4
DATAE5HA6H6BVT4_0: dc.b $2
	dc.b $FC, $C, $0, $0, $F0
	dc.b $F4, $3, $0, $0, $9B
	even