; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Jun 09 2020 13:09:45 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATATXVL0OC1P8:
	dc.w DATATXVL0OC1P8_0-DATATXVL0OC1P8, DATATXVL0OC1P8_1-DATATXVL0OC1P8
	dc.w DATATXVL0OC1P8_2-DATATXVL0OC1P8, DATATXVL0OC1P8_3-DATATXVL0OC1P8
	dc.w DATATXVL0OC1P8_4-DATATXVL0OC1P8, DATATXVL0OC1P8_5-DATATXVL0OC1P8
DATATXVL0OC1P8_0: dc.b $2
	dc.b $F8, $C, $0, $0, $F0
	dc.b $0, $C, $0, $4, $F0
DATATXVL0OC1P8_1: dc.b $1
	dc.b $0, $C, $0, $0, $F0
DATATXVL0OC1P8_2: dc.b $3
	dc.b $E8, $C, $0, $0, $F0
	dc.b $F0, $5, $0, $8, $F8
	dc.b $0, $C, $0, $C, $F0
DATATXVL0OC1P8_3: dc.b $1
	dc.b $F0, $7, $0, $0, $F8
DATATXVL0OC1P8_4: dc.b $1
	dc.b $F0, $3, $0, $4, $F8
DATATXVL0OC1P8_5: dc.b $4
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $9, $0, $8, $F8
	dc.b $F0, $0, $0, $0, $F8
	dc.b $8, $0, $0, $3, $F8
	even